// Chrome extensions cannot import outside their root. Bundle the canonical,
// dependency-free Studio renderer without changing its implementation.
import { readFile, writeFile, rename, rm } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export async function cursorBundle() {
  const parts = await Promise.all(['motions.js', 'config.js', 'engine.js'].map(
    file => readFile(resolve(root, 'extension/vendor/cursor-studio', file), 'utf8')));
  const body = parts.map(source => source.replace(/\r\n/g, '\n').replace(/^import .*?;\n/gm, '')
    .replace(/^export /gm, '')).join('\n');
  return '// Generated by scripts/sync-cursor.mjs from versioned vendor/cursor-studio sources. Do not edit.\n'
    + 'export function cursorRuntime() {\n' + body
    + '\nreturn { Character, defaults, validatePack, poseFor, drawCursor };\n}\n';
}
export async function syncCursor(check = false) {
  const target = resolve(root, 'extension/character-runtime.mjs');
  const source = await cursorBundle();
  if (check) {
    if ((await readFile(target, 'utf8')).replace(/\r\n/g, '\n') !== source) throw Error('Cursor renderer is stale. Run npm run sync:cursor.');
  } else {
    // Multiple standalone MCP clients can start together. Do not truncate a
    // module that Chrome may be loading, or rewrite an unchanged extension.
    try {
      if ((await readFile(target, 'utf8')).replace(/\r\n/g, '\n') === source) return;
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    const temporary = target + '.' + randomUUID() + '.tmp';
    try {
      await writeFile(temporary, source);
      await rename(temporary, target);
    } finally {
      await rm(temporary, { force: true });
    }
  }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await syncCursor(process.argv.includes('--check'));
}
